### ISSUE TITLE
Page http://newsletter.wedeploy.io not found

### ISSUE THREAD

**Issue by anarute** [wedeploy/demo-newsletter#3]
I assume that maybe is too soon, but since the link is there, I'm curious to see the demo working, is it ready? :) If yes I can try running locally, should I follow the steps on https://wedeploy.com/docs/email/getting-started/ ?

**Comment by zenorocha** [comment]
Sorry about that @anarute, here's the demo working on this new URL: https://ui-newsletter.wedeploy.io/

If you're starting with WeDeploy, my suggestion is to follow this tutorial:
https://wedeploy.com/tutorials/email-web/get-started/

It will teach you step by step how to send emails. And, please, if you have any questions, let me know.
